name: Build Mod
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Cập nhật lên v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4 # Cập nhật lên v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: chmod +x gradlew && ./gradlew build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # ĐÂY LÀ CHỖ QUAN TRỌNG NHẤT - Sửa thành v4
        with:
          name: ModJar
          path: build/libs/*.jar
